### PR TITLE
Move to Discord GameSDK

### PR DESCRIPTION
**Pull request by Almighty-Alpaca**
This PR draft is to track the progress and provide a place for comments

### CODE REVIEW

**Comment by RemainingToast** [comment]
Is this still being worked on?

**Comment by Almighty-Alpaca** [comment]
Yup, it's still being worked on. Due to other obligations I wasn't able to invest much time lately, but that'll change soon™.

**Comment by JasonLovesDoggo** [comment]
any update?

**Comment by seailz** [comment]
Anything?

**Pull request closed without merging**
