### PR TITLE
Implement templates for custom fields

### PR DESCRIPTION
**Pull request by dblanovschi**

### CODE REVIEW

**Comment by Clashsoft** [comment]
Is there a reason why this invents a new template language, instead of using an existing one?

**Comment by Almighty-Alpaca** [comment]
@Clashsoft do you have any particular one in mind?

The problem I have with most existing templating languages is that they tend to be very complex. To create simple short strings you don't need functions, loops, etc. In my opinion simple variable substitution and conditions are enough for that. 

That being said I do have a few ideas on how to make the syntax simpler.

**Comment by Clashsoft** [comment]
IntelliJ already uses [Velocity](http://velocity.apache.org/) for live and file templates. Maybe there is already a builtin parser available for plugin authors? If not, you should at least aim for a subset of the syntax.

**Comment by Almighty-Alpaca** [comment]
Velocity is a good example for a language that's way to complex for this use case. I also think that the benefits of using it would only be marginal since most people probably aren't even aware of Velocity and it's usage in IntelliJ.

**Comment by Clashsoft** [comment]
I agree that Velocity may be too complex for this use case, but the complexity of a new template language is far greater in terms of maintenance. The changes introduced here pull in ANTLR, are sometimes deeply nested (https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/pull/108/files#diff-4f35320e8bfe3063b33cad347ee8107eR86) and require significant documentation, which needs to be read by both developers and users. Velocity was only an idea, my suggestion is about not reinventing the wheel in general and using a solution that already exists.

**Comment by dblanovschi** [comment]
> but the complexity of a new template language is far greater in terms of maintenance.

I tried to keep it as simple as possible. I may be wrong on this, but I think as long as it doesn't get too complex, maintaining it will not be such a big issue(and would maintain it myself, should the need arise).

> The changes introduced here pull in ANTLR

ANTLR was used to replace [the old lexer and parser](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/2c879c815233f3e85d8400d90bef953b071c5c0e/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/render/templates/CustomTemplate.kt#L220-L283), which were a mess to both maintain and work with(sorry for that).

**Review by Almighty-Alpaca — APPROVED** [review]

**Pull request merged**
