### PR TITLE
Update Dart Lang Icon

### PR DESCRIPTION
**Pull request by doch2**
Replace the icon of the Dart language, which was an old version.

### CODE REVIEW

**Comment by CoderJava** [comment]
Please approve this PR. I need this.

**Comment by doch2** [comment]
@Almighty-Alpaca Please check and approve this PR.

**Comment by InfRandomness** [comment]
This looks good to me, but changing the logo in the repository is only half the battle, it needs to be changed on the discord developer portal as well
This task can only be done by alpaca himself as he is the owner of the application containing all of the resources that the plugin uses

**Comment by doch2** [comment]
> This looks good to me, but changing the logo in the repository is only half the battle, it needs to be changed on the discord developer portal as well This task can only be done by alpaca himself as he is the owner of the application containing all of the resources that the plugin uses

You're right. I want the person in charge of this project to merge this PR, and modify the icon on the Discord Developer Portal.

**Review by Almighty-Alpaca — APPROVED** [review]

**Review by Juliotati — COMMENTED** [review]
**NICE!**

**Pull request merged**
