### PR TITLE
Update discord-ipc

### PR DESCRIPTION
**Pull request by DeDiamondPro**
This fixes an error for people with nitro basic, specifically this error:
```
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:43)
	at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
	at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
	at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
	at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
	at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
	at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at dev.cbyrne.kdiscordipc.core.packet.pipeline.ByteToMessageDecoder.decode(ByteToMessageDecoder.kt:23)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:36)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### CODE REVIEW

**Comment by dayo05** [comment]
Related issues: #263 #300

**Comment by Mattwmaster58** [comment]
@Almighty-Alpaca anything holding this back?

**Comment by itsTyrion** [comment]
[JetBrains-Discord-Integration-1.11.0+2.zip](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/files/11290764/JetBrains-Discord-Integration-1.11.0%2B2.zip)
I built it in case anyone wants it without downloading all the gradle deps (which include a full copy of IntelliJ!)

**Comment by cancel-cloud** [comment]
@Almighty-Alpaca is there something, which needs to be done first?

**Comment by DreamTexX** [comment]
When will this be merged?

**Comment by caoimhebyrne** [comment]
Superceeded by https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/pull/386

**Comment by itsTyrion** [comment]
the project is abandoned. try this fork https://github.com/Azn9/JetBrains-Discord-Integration

**Comment by Almighty-Alpaca** [comment]
Closing in favor of #386

**Pull request closed without merging**
